import type { UIManifest } from "./manifest";

export const mockManifest: UIManifest = {
  version: "1.0",
  sourceImage: { width: 390, height: 844, path: "mock" },
  theme: {
    colors: ["#111827", "#2563eb", "#10b981", "#ffffff"],
    fontStyle: "modern sans",
    radius: [12, 18, 22],
    shadowStyle: "soft elevation",
  },
  elements: [
    {
      id: "profile_avatar",
      type: "avatar",
      bbox: [22, 42, 42, 42],
      strategy: "crop",
      confidence: 0.91,
      reason: "头像属于不可替代图片资产，优先从原图裁剪。",
      needsReview: false,
    },
    {
      id: "search_icon_button",
      type: "icon",
      bbox: [332, 45, 36, 36],
      strategy: "asset",
      confidence: 0.82,
      reason: "图标需要从原图截取为素材，不再匹配图标库。",
      needsReview: true,
    },
    {
      id: "hero_background",
      type: "background",
      bbox: [22, 116, 346, 170],
      strategy: "regenerate",
      confidence: 0.78,
      reason: "复杂渐变背景和光效适合重绘为独立资产。",
      prompt:
        "Create a clean abstract mobile app hero background with blue cyan green gradient, soft glow, no text, 390x170 aspect ratio.",
      needsReview: true,
    },
    {
      id: "category_tabs",
      type: "tabbar",
      bbox: [22, 314, 239, 32],
      strategy: "code",
      confidence: 0.94,
      reason: "Tab 控件应该用真实 HTML/CSS 实现。",
      needsReview: false,
    },
    {
      id: "list_card_1",
      type: "card",
      bbox: [22, 372, 346, 86],
      strategy: "code",
      confidence: 0.96,
      reason: "卡片容器、文本和阴影都适合 CSS 实现。",
      needsReview: false,
    },
    {
      id: "card_1_thumbnail",
      type: "illustration",
      bbox: [38, 387, 56, 56],
      strategy: "crop",
      confidence: 0.88,
      reason: "卡片缩略图可以从原图裁剪，保持风格一致。",
      needsReview: false,
    },
    {
      id: "list_card_2",
      type: "card",
      bbox: [22, 474, 346, 86],
      strategy: "code",
      confidence: 0.95,
      reason: "重复卡片结构适合代码复用。",
      needsReview: false,
    },
    {
      id: "card_2_thumbnail",
      type: "illustration",
      bbox: [38, 489, 56, 56],
      strategy: "crop",
      confidence: 0.86,
      reason: "卡片缩略图可以从原图裁剪。",
      needsReview: false,
    },
    {
      id: "bottom_navigation",
      type: "navbar",
      bbox: [22, 760, 346, 62],
      strategy: "code",
      confidence: 0.92,
      reason: "底部导航是交互控件，必须代码化。",
      needsReview: false,
    },
  ],
};
